Missing whitespace breaks angular
On Angular version 14, returns following error: 

./src/styles.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected whitespace.
   ╷
99 │     @media screen and(min-width: $layout-window-mode-max-width + 150px) {
   │                      ^
   ╵

Adding whitespace to line 99 fixes issue.